---
title: 'Part 1: District NPEV prevalence'
subtitle: '1A: Descriptive'
output:
  html_document:
    df_print: paged
---

```{r}

pacman::p_load(tidyverse, here, gtsummary, sf, spdep, patchwork)
theme_set(theme_minimal())

dir <- "data/Pakistan"
figdir <- "figures/descriptive/afp"

# NP-AFP analysis data
data <- readRDS(here(dir, "analyis/prevalence/afp_analysis.rds"))

# Shapefiles and adjacency matrix
shape2 <- readRDS(here(dir,"shape2.rds")) |> st_transform(4326)

```

## Table 1

```{r}

data |> 
  tbl_summary(include = c(n_afp, n_npafp, npafp_r, n_ev, ev_afp_p, n_npev, npev_npafp_p),
              by = year,
              label = list(n_afp = "AFP notifications", 
                           n_npafp = "Non-polio AFP notifications", 
                           npafp_r = "Non-polio AFP rate (per 100,000 U15s)", , 
                           n_ev = "EV positives", 
                           ev_afp_p = "Crude EV prevalence",
                           n_npev = "NPEV positives", 
                           npev_npafp_p = "Crude NPEV prevalence")) |> 
  add_overall() |> 
  as_gt()

```

Plot crude NPEV prevalence among notified non-polio AFP cases, per district and over time:

```{r}

# Overall AFP/NPAFP rates
data |> 
  group_by(month) |> 
  summarise(across(c("n_afp","n_npafp", "denominator"), sum)) |> 
  pivot_longer(n_afp:n_npafp) |> 
  mutate(name = factor(name, labels = c("AFP","NP-AFP")),
         r = value*1e5/denominator) |> 
  rowwise() |> 
  mutate(lo = Hmisc::binconf(value, denominator)[2]*1e5,
         hi = Hmisc::binconf(value, denominator)[3]*1e5) |>
  ggplot(aes(month, r, ymin = lo, ymax = hi)) +
  geom_ribbon(alpha = 0.2) +
  geom_line(aes(lty = name, col = name)) + 
  guides(color = guide_legend(NULL),
         lty = guide_legend(NULL)) +
  scale_colour_manual(values = c("black","red")) +
  scale_linetype_manual(values = c("solid","dashed")) + 
  theme(legend.position = c(0.2,0.9)) +
  labs(x = "Month", y = "Rate per 100,000") -> p_afp_rates

# Proportion PV+
data |> 
  group_by(month) |> 
  summarise(afp = sum(n_afp),
            npafp = sum(n_npafp),
            pv = afp - npafp) |> 
  pivot_longer(npafp:pv) |> 
  mutate(name = factor(name, labels = c("Non-polio","Polio"))) |> 
  ggplot(aes(month, value, fill = name)) +
  geom_col(position = position_dodge()) +
  scale_fill_manual(values = c("grey", "black")) +
  scale_y_continuous(trans = "sqrt") +
  theme(legend.position = c(0.2,0.9)) +
  labs(x = "Month", y = "No. AFP notifications", fill = NULL) -> p_pvpos

# Annual NPEV+ rate by district
data |> 
  group_by(guid, year) |> 
  summarise(n_npafp = sum(n_npafp),
            n_npev = sum(n_npev),
            r_npev = n_npev/n_npafp) |>
  ungroup() |>
  right_join(shape2) |> 
  ggplot(aes(fill = r_npev, geometry = SHAPE)) + 
  geom_sf(col = NA) +
  facet_wrap(~year) +
  scale_fill_viridis_c(name = "NPEV+\nPrevalence", trans = "sqrt") + 
  theme_void() -> p_dist_yr


# Longer term trend, by province
data |> 
  group_by(month, adm1_name) |> 
  summarise(n_npafp = sum(n_npafp),
            n_npev = sum(n_npev),
            r_npev = n_npev/n_npafp) |>
  ungroup() |>
  ggplot(aes(x = month, y = r_npev, 
             group = adm1_name, col = adm1_name, fill = adm1_name)) + 
  # geom_jitter(alpha = 0.2) + 
  geom_smooth(alpha = 0.3) + 
  labs(x = NULL, y = "NPEV+ Prevalence") -> p_mth_prov

# Correlation with population density
data |> 
  group_by(guid_pop_dens, guid) |> 
  summarise(n_npafp = sum(n_npafp),
            n_npev = sum(n_npev),
            r_npev = n_npev/n_npafp) |>
  ungroup() |>
  ggplot(aes(x = as.numeric(guid_pop_dens), y = r_npev)) + 
  geom_jitter(alpha = 0.2) +
  geom_smooth(alpha = 0.1, lwd = 0.2, se = T) + 
  scale_x_continuous(trans = "log10") +
  labs(x = "Log population density (/km2)", y = "NPEV+ Prevalence") -> p_dens_dist

p_afp_rates
p_pvpos
p_mth_prov
p_dens_dist

```

Seasonal trends
```{r}

# Seasonal trend, overall
data |> 
  group_by(month_of_year) |> 
  summarise(n_npafp = sum(n_npafp),
            `NPEV+` = sum(n_npev),
            `NPEV-` = n_npafp - `NPEV+`,
            p_npev = `NPEV+`*100/n_npafp) |>
  ungroup() |> 
  pivot_longer(`NPEV+`:`NPEV-`) |>
  ggplot() + 
  geom_col(aes(x = month_of_year, y = value,  fill = name)) +
  geom_line(aes(x = month_of_year, y = p_npev*150, group = 1),
            col = viridis::mako(5, end = 0.8)[3], lwd = 1) +
  scale_fill_manual(values = c("grey","grey50")) +
  scale_y_continuous(name = "Notified NP-AFP cases",
                     sec.axis = sec_axis(trans=~./150,
                                         name = NULL)) +
  theme(legend.position = c(0.2,0.9)) +
  labs(x = "Paralysis onset month", y = "Count", fill = NULL) -> p_moy

# Seasonal trend, by year
data |> 
  group_by(month_of_year, year) |> 
  summarise(n_npafp = sum(n_npafp),
            n_npev = sum(n_npev),
            r_npev = n_npev*100/n_npafp) |>
  ungroup() |>
  ggplot(aes(x = month_of_year, y = r_npev, 
             group = factor(year), col = factor(year))) + 
  geom_point() + 
  geom_smooth(se = F) + 
  scale_colour_viridis_d(option = "mako", end = 0.8) +
  scale_fill_viridis_d(option = "mako", end = 0.8) +
  theme(legend.position = c(0.9,0.85)) +
  # guides(fill = "none") +
  ylim(0,100) +
  labs(x = "Paralysis onset month", y = "% Positive", col = NULL) -> p_moy_yr

# Seasonal trend, by province
data |> 
  group_by(month_of_year, adm1_name) |> 
  summarise(n_npafp = sum(n_npafp),
            n_npev = sum(n_npev),
            r_npev = n_npev/n_npafp) |>
  ungroup() |>
  ggplot(aes(x = month_of_year, y = r_npev, 
             group = adm1_name, col = adm1_name, fill = adm1_name)) + 
  # geom_jitter(alpha = 0.2) + 
  geom_smooth(alpha = 0.5) + 
  labs(x = NULL, y = "NPEV+ Prevalence") -> p_moy_prov

# Seasonal trend, by district
data |> 
  group_by(month_of_year, guid) |> 
  summarise(n_npafp = sum(n_npafp),
            n_npev = sum(n_npev),
            r_npev = n_npev/n_npafp) |>
  ungroup() |>
  ggplot(aes(x = month_of_year, y = r_npev, 
             group = guid)) + 
  # geom_jitter(alpha = 0.2) + 
  geom_smooth(alpha = 0.1, lwd = 0.2, se = F, 
              col = "steelblue") + 
  theme(axis.text.x = element_text(angle = 45)) +
  labs(x = NULL, y = "NPEV+ Prevalence") -> p_moy_dist


p_moy
p_moy_yr
p_moy_prov
p_moy_dist

```

Overall decrease year on year, with more pronounced seasonality in 2021. 

```{r}

p_moy + p_moy_yr + 
  plot_annotation(tag_levels = "A") -> p_seas_npev

p_seas_npev
saveRDS(p_seas_npev, here(figdir,"plotobj/npev_seas.png"))
ggsave(here(figdir,"npev_seas.png"),
       height = 4, width = 10, bg = "white")

```

## Figure 1

```{r}

(p_afp_rates + p_pvpos)/
  (p_dist_yr + p_moy_dist) +
  plot_annotation(tag_levels = "A")
ggsave(figdir,"Figure_1.png", 
       bg = "white",
       height = 6, width = 8, units = "in")

```

################################################################################
################################################################################